// Parity tests for the browser port (BROWSER_PORT_PLAN.md).
// Replays PyTorch/numpy reference vectors (generated by export_web_weights.py)
// against the JS filter implementations, plus seeded behavioral checks.
//
// Run:  node web/test/parity.mjs        (no dependencies, plain node)

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const here  = dirname(fileURLToPath(import.meta.url));
const jsDir = join(here, '..', 'js');
const load  = p => JSON.parse(readFileSync(join(here, p), 'utf8'));

// Evaluate the browser sources in one shared context, like <script> tags.
const ctx = vm.createContext({ console });
for (const f of ['mat.js', 'kf.js', 'kalmannet.js', 'sim.js'])
  vm.runInContext(readFileSync(join(jsDir, f), 'utf8'), ctx, { filename: f });
const { KalmanFilter, KalmanNET, DroneSim } =
  vm.runInContext('({ KalmanFilter, KalmanNET, DroneSim })', ctx);

const weights = load('../weights.json');

let failures = 0;
function check(name, cond, detail) {
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${name}${detail ? '  (' + detail + ')' : ''}`);
  if (!cond) failures++;
}

// ── 1. Classical KF vs numpy (both float64 — near bit-exact) ─────────────────
{
  const ref = load('reference_kf.json');
  const kf = new KalmanFilter();
  kf.x = ref.x0.slice();
  let maxX = 0;
  for (const s of ref.steps) {
    kf.predict();
    for (const name of s.active) kf.update(name, s.z[name]);
    for (let i = 0; i < 6; i++) maxX = Math.max(maxX, Math.abs(kf.x[i] - s.x[i]));
  }
  let maxP = 0;
  for (let i = 0; i < 6; i++)
    for (let j = 0; j < 6; j++) maxP = Math.max(maxP, Math.abs(kf.P[i][j] - ref.P_final[i][j]));
  check('KF state parity, 200 steps w/ dropouts', maxX < 1e-9, `max |Δx| = ${maxX.toExponential(2)}`);
  check('KF covariance parity (final P)',         maxP < 1e-9, `max |ΔP| = ${maxP.toExponential(2)}`);
}

// ── 2. GRU + heads vs torch (float32 net, float64 port — tolerance) ──────────
{
  const ref = load('reference_gru.json');
  const kn = new KalmanNET();
  kn.loadWeights(weights);
  let maxK = 0;
  for (const s of ref.steps) {
    const K = kn._gruForward(s.iv9);
    for (const sensor of Object.keys(s.K))
      for (let i = 0; i < s.K[sensor].length; i++)
        for (let j = 0; j < s.K[sensor][i].length; j++)
          maxK = Math.max(maxK, Math.abs(K[sensor][i][j] - s.K[sensor][i][j]));
  }
  let maxH = 0;
  for (let i = 0; i < ref.h_final.length; i++)
    maxH = Math.max(maxH, Math.abs(kn._h[i] - ref.h_final[i]));
  check('GRU K-output parity, 100 steps', maxK < 1e-4, `max |ΔK| = ${maxK.toExponential(2)}`);
  check('GRU hidden-state parity (final h)', maxH < 1e-4, `max |Δh| = ${maxH.toExponential(2)}`);
}

// ── 3. Trained KalmanNET end-to-end vs Python (clip + Joseph + guard path) ───
{
  const ref = load('reference_knstep.json');
  const kn = new KalmanNET();
  kn.loadWeights(weights);
  kn.reset(ref.x0);
  let maxX = 0, maxR = 0;
  for (const s of ref.steps) {
    const zv = {};
    for (const name of s.active) zv[name] = s.z[name];
    kn.step(zv);
    for (let i = 0; i < 6; i++) maxX = Math.max(maxX, Math.abs(kn._kf.x[i] - s.x[i]));
    for (const sensor of Object.keys(s.k_ratio))
      for (let j = 0; j < s.k_ratio[sensor].length; j++)
        maxR = Math.max(maxR, Math.abs(kn._kRatio[sensor][j] - s.k_ratio[sensor][j]));
  }
  check('KalmanNET end-to-end state parity, 300 steps', maxX < 0.05, `max |Δx| = ${maxX.toExponential(2)} m`);
  check('KalmanNET k-ratio parity', maxR < 0.05, `max |Δratio| = ${maxR.toExponential(2)}`);
}

// ── 4. Untrained fallback must be EXACTLY the classical KF ───────────────────
{
  const rng = mulberry32(11);
  const kn = new KalmanNET();          // no weights loaded → untrained
  const kf = new KalmanFilter();
  const h0 = [20, 0, 0, 0, 6, 1];
  kn.reset(h0);
  kf.x = h0.slice();
  let maxX = 0;
  for (let i = 0; i < 100; i++) {
    const z = {
      gps:  [20 + rng() * 4, rng() * 4, i * 0.05 + rng()],
      imu:  [rng() - 0.5, 6 + rng() - 0.5, 1 + rng() - 0.5],
      baro: [i * 0.05 + rng() - 0.5],
      mag:  [20 + rng() * 6 - 3, rng() * 6 - 3],
    };
    if (i % 5 === 2) delete z.gps;   // partial-update coverage
    kn.step(z);
    kf.predict();
    for (const name of ['gps', 'imu', 'baro', 'mag'])
      if (z[name]) kf.update(name, z[name]);
    for (let j = 0; j < 6; j++) maxX = Math.max(maxX, Math.abs(kn._kf.x[j] - kf.x[j]));
  }
  check('untrained fallback ≡ classical KF', maxX < 1e-12, `max |Δx| = ${maxX.toExponential(2)}`);
}

// ── 5. Behavioral: seeded sim runs reproduce the demo's claims ───────────────
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

{
  // Untrained, calm: KF error settles to low single-digit metres.
  const sim = new DroneSim(0.05, { random: mulberry32(1) });
  let sum = 0, n = 0;
  for (let i = 0; i < 400; i++) {
    const s = sim.step();
    if (i >= 200) { sum += s.error; n++; }
  }
  const mean = sum / n;
  check('untrained sim @ calm: mean KF error < 3 m', mean < 3, `mean = ${mean.toFixed(2)} m`);
}

{
  // Trained, +30 °C baro bias: KN must beat KF (the demo's core claim).
  const sim = new DroneSim(0.05, { random: mulberry32(2) });
  sim.kn.loadWeights(weights);
  sim.setEnvironment(0, 0, 50);
  let kfSum = 0, knSum = 0, n = 0;
  for (let i = 0; i < 1200; i++) {
    const s = sim.step();
    if (i >= 200) { kfSum += s.error; knSum += s.kn_error; n++; }
  }
  const kfMean = kfSum / n, knMean = knSum / n;
  check('trained sim @ 50°C: KN error < KF error', knMean < kfMean,
        `KN = ${knMean.toFixed(2)} m, KF = ${kfMean.toFixed(2)} m`);
}

console.log(failures ? `\n${failures} FAILURE(S)` : '\nall parity tests passed');
process.exit(failures ? 1 : 0);
